### ISSUE TITLE
limited quantity of playlists and my work around ceased working

### ISSUE THREAD

**Issue by GayLemonade** [TomerAberbach/spotify-true-random#14]
I have found that there is a limit to the playlist selector only allowing me to select from 50 of my playlists. I had previously made the workaround of pinning the playlist in my library when I wanted to play it so it would show up at the top of the true random playlist selector. it stopped updating the list of playlists when I do that even after I cleared cache, restarted browser, refreshed page ect
I recognize this isn't your most important project right now lol, this work of yours has served me well and I just can't imagine life without it. if you're able to iron out some wrinkles for me that would be incredible. thank you for your work tomer aberbach.
![Screenshot_20240620_134211_Chrome](https://github.com/TomerAberbach/spotify-true-random/assets/173396063/b2a3a788-2d11-4d4f-9b13-d57930775eb4)
![Screenshot_20240620_134228_Spotify](https://github.com/TomerAberbach/spotify-true-random/assets/173396063/e8d1824d-55da-4aeb-beac-4f54a3116a28)

**Comment by GayLemonade** [comment]
I should also mention that I too experience a problem from a previous post where if a playlist has a local file in it it just won't play the playlist at all

**Comment by TomerAberbach** [comment]
First, you have some A+ playlist names haha

I looked at my code and looks like I do only get the first 50 playlists... Maybe Spotify changed how they consider which playlists are the "first" 50 and that's why you're seeing this. Have you tried actually reordering the playlists by dragging them instead of pinning? Maybe that would make Spotify respect the order? Not sure honestly!

I wrote this code like 6 years ago when I was in college so it's not in the most ideal state truthfully. I've considered going back and rewriting/improving it so that it doesn't have all these issues, but haven't gotten around to it. I might try to do that in the near future, but no promises

**Comment by GayLemonade** [comment]
I figured it was one of those things where the code is older and hard to work with lol. 
it does seem that reordering the custom order on desktop makes playlists from long ago appear in the list on the mobile true randomizer. I wonder why the pinning playlists stopped working like it did before, when I change pinned playlist it takes like 24 hours to appear on the true randomizer instead of instant like it did befire. it's not a perfect workaround because it does mean you have to have access to the desktop app if you want to play a playlist that's not in your first 50. BUT for others with this problem it is a workaround which is better than none. 
appreciate the help! your work will still continue to be life changing for my music listening even if you don't get around to updating it's code soon so no worries. thank you!

**Comment by TomerAberbach** [comment]
Alright I decided to take the time to do this. I just spent a few hours rewriting this with modern stuff. The new website will be at this URL:

https://spotify-true-random.tomeraberba.ch

I'm planning to set up a redirect from the old URL to this new one to carry over existing users. It should get all the playlists (not just the first 50) and it should skip local tracks (since there's no way to play those via the API) instead of erroring.

Can you try it out and let me know if things are working for you? Wanna confirm it's working for others before setting up the redirect

**Comment by GayLemonade** [comment]
omg this is excellent I can see all my own playlists and they all play fine thank you very much. I have tested the link out and here are the overly in depth results of my testing:

play button did appear on the second line instead of the first on my mobile phone (could have been intentional or not either way it really does not matter in my opinion it's just in a difference I noticed)

I added a local file to my big favorite songs playlist and it does not error (tested it twice)

I made a new playlist with non local songs and that played fine. 

I renamed a playlist and it updated just fine after a refresh 

I did get an error where it would perpetually show that it was queueing a playlist, specifically if I made a new playlist and added both normal and local songs to it (tested that twice too). which is really strange because when I added local files to an older playlist earlier, it skips the local files like it's supposed to. so that just seems to be a very extremely minor error.

also it's still confused about pinned playlists, it's showing my top playlists as the ones I had pinned yesterday, not right now. worst case scenario that just makes the top four playlists not match up right, since I can see all the playlists now that doesn't bother ME.

I am personally VERY SATISFIED with the update and appreciate it greatly. I don't think any of the small differences above are anything to stress yourself out over at all (especially if they're a nightmare to fix), because the website is still an amazing tool that now works even better than before. I'm just reporting minor things you may want to be aware of is all.

thank you again!

**Comment by TomerAberbach** [comment]
> omg this is excellent I can see all my own playlists and they all play fine thank you very much. I have tested the link out and here are the overly in depth results of my testing:
> 
> play button did appear on the second line instead of the first on my mobile phone (could have been intentional or not either way it really does not matter in my opinion it's just in a difference I noticed)

Yup, intentional. Felt it looked better to group it with the dropdown that it refers to.

> I added a local file to my big favorite songs playlist and it does not error (tested it twice)
> 
> I made a new playlist with non local songs and that played fine.
> 
> I renamed a playlist and it updated just fine after a refresh
> 
> I did get an error where it would perpetually show that it was queueing a playlist, specifically if I made a new playlist and added both normal and local songs to it (tested that twice too). which is really strange because when I added local files to an older playlist earlier, it skips the local files like it's supposed to. so that just seems to be a very extremely minor error.

That's odd... I'll keep an eye out for errors, but if it generally works, then that sounds okay I guess 🤷 

> also it's still confused about pinned playlists, it's showing my top playlists as the ones I had pinned yesterday, not right now. worst case scenario that just makes the top four playlists not match up right, since I can see all the playlists now that doesn't bother ME.

Yeah, I think that's just a Spotify API issue that they return the playlists in a weird order. Not sure there's much that can be done about that on my end. [Feel free to file an issue with Spotify](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer) if you care enough about that.

> I am personally VERY SATISFIED with the update and appreciate it greatly. I don't think any of the small differences above are anything to stress yourself out over at all (especially if they're a nightmare to fix), because the website is still an amazing tool that now works even better than before. I'm just reporting minor things you may want to be aware of is all.
> 
> thank you again!

Glad to hear! I'll set up a redirect from the old website to the new one soon

**Comment by TomerAberbach** [comment]
Redirect is set up
