### ISSUE TITLE
song limit #2

### ISSUE THREAD

**Issue by GayLemonade** [TomerAberbach/spotify-true-random#17]
so I'm looking through the same mega playlist I have (hugging and a kissing dancing and a loving) and I noticed that as I scroll down it's around the 380th (ish) that the songs start to become more unrecognizable to me. for example I've got 6 Sabrina Carpenter songs I added 3 weeks ago to the playlist I listen to every day and I've heard none of them in the shuffle.

I tested further by clicking the shuffle button and counting how many songs would play before the queue stopped. and weirdly enough it is 382. my playlist is 459 songs right now and so those last 77 aren't recognizable to me because they're not getting seen when picking the queue.

I've also tested by shuffling 3 times and searched the whole queue for 4 any of those 6 Sabrina Carpenter songs and the queue ends before it gets to them. 

and I also don't believe the issue is related to the date added because songs 380, 381, and 382 were added August 7th and those ones play fine. but 383 and past do not.

again I love this project and I am so appreciative of you for creating it. and I am SO sorry to be pointing out so many bugs to you but if you could be an absolute angel and just see if it's fixable that would be heavenly. thank you so much ❤️

**Comment by TomerAberbach** [comment]
So you are 100% correct that I (purposefully) cut off at [382 songs](https://github.com/TomerAberbach/spotify-true-random/blob/main/src/services/spotify.ts#L78-L80) because of a Spotify limitation around how many songs can be played. The fact that songs are still playing afterwards is probably because you have the Autoplay setting enabled:
![Screenshot 2024-09-19 at 4 55 06 PM](https://github.com/user-attachments/assets/d8ba55b5-c556-4e1f-beb4-72da8b3fe9d3)

I am now realizing though that I should have fetched all the songs, then shuffled, _then_ cut off at 382 songs. That way at least we're still shuffling all the songs, rather than just the first 382. I'll at least do that, but I'll also check if I can figure out how to add more than 382 songs to the queue. Maybe I can make multiple calls to Spotify or something.

P.S. Thanks for the sponsor :)

**Comment by TomerAberbach** [comment]
Okay, so I just pushed an update that will fetch _all_ tracks, shuffle, limit to 382 tracks, then play instead of fetch first 382 tracks, shuffle, then play. That doesn't solve the fact that it only queues 382 tracks, but it does solve that it wasn't actually shuffling the whole playlist (for really large ones)

**Comment by TomerAberbach** [comment]
I looked through the Spotify API a bit and I don't think there's a straightforward way to queue more than 382 songs.

I'm using the [start/resume playback endpoint](https://developer.spotify.com/documentation/web-api/reference/start-a-users-playback) because it allows sending multiple track URIs in one request. However, it doesn't seem to support using multiple requests to queue multiple batches of 382 songs. Each batch overwrites the previous one.

There is actually a [dedicated endpoint for adding to the playback queue](https://developer.spotify.com/documentation/web-api/reference/add-to-queue), but it only supports adding one track at a time. I don't think I can reliably make 1000 requests to Spotify for a 1000 track playlist, so the current setup seems better.

Thus, I am closing this issue because I think the main problem (of not actually shuffling the whole playlist) has been fixed.
